### ISSUE TITLE
Hangfire Graph empty

### ISSUE THREAD

**Issue by Calabonga** [MassTransit/Sample-Hangfire#1]
What I did: 
► I upgraded solution projects to NET 6.0. 
► I changed BackgroundWorker could send message every 10 seconds. 
► Then I started solution in debug mode. 
► After that I opened URL "/hangfire", but nothing found on the  graph!

![image](https://github.com/MassTransit/Sample-Hangfire/assets/346209/e65e6e03-7986-478a-9608-18f3d84269e7)

Question: Is this how it should be or am I setting something up wrong?

**Comment by Calabonga** [comment]
Correct configuration - was fix the issue. Sorry. By the way, I can push pull request with net6 migrated solution. But I have no permission to do it. Is it interesting?

**Comment by Calabonga** [comment]
Correct configuration - was fix the issue. Sorry. By the way, I can push pull request with net6 migrated solution. But I have no permission to do it. Is it interesting?

**Comment by phatboyg** [comment]
You're welcome to create a PR, you just need to fork the repository and push the PR to your branch.
