### ISSUE TITLE
Hangfire worker count 

### ISSUE THREAD

**Issue by yavuz-soylu-crea** [MassTransit/Sample-Hangfire#3]
Is there a way to reduce hangfire worker count?
![image](https://github.com/MassTransit/Sample-Hangfire/assets/105991251/66c47ed2-c8f3-4a63-9b95-75ec848a7797)

**Comment by phatboyg** [comment]
That's something you'd configure in Hangfire, not MassTransit.

**Comment by yavuz-soylu-crea** [comment]
Thank you for response, , but the worker count configured in Hangfire does not change the worker count of the server created for masstransit.
![image](https://github.com/MassTransit/Sample-Hangfire/assets/105991251/80d4772f-c42f-4b71-91d7-cf1980ed2d67)

This is the configuration code that works for hangfire server but does not affect masstransit's hangfire server configuration
 ```
       services.AddHangfireServer(opt =>
        {
            opt.WorkerCount = 1; 
            opt.SchedulePollingInterval = TimeSpan.FromMinutes(15);
        });
```

I tried to intervene by giving the queue name with a different config, but since the server name was also required, I could not try it exactly, because the server name for masstransit is given by masstransit.

        services.AddHangfireServer(opt =>
        {
            opt.ServerName = string.Format("{0}:mt-message-queue", Environment.MachineName);// required
            opt.Queues = new[] { "mt-message-queue" };
            opt.WorkerCount = 1;
            opt.SchedulePollingInterval = TimeSpan.FromMinutes(15);
        });

**Comment by phatboyg** [comment]
Make sure you're configuring MassTransit correctly:

https://masstransit.io/documentation/configuration/scheduling#hangfire
